music/urls.py
from django.urls import path
from . import views
app_name = 'music'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),


    path('register/',views.UserFormView.as_view(),name='register'),


    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    #add
    path('album/add/', views.AlbumCreate.as_view(),name='album-add'),

    #update
    path('album/<int:pk>/', views.AlbumUpdate.as_view(),name='album-update'),

    #delete
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(),name='album-delete'),
    #path('<int:album_id>/',views.detail,name='detail'),

    #path('<int:album_id>/favorite/',views.favorite,name='favorite'),
    #path('<int:pk>/',views.DetailView.as_view(),name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),

]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse
from django.urls import reverse_lazy

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=300)
    genre = models.CharField(max_length=150)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=300)
    song_title = models.CharField(max_length=300)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

myapp/models.py
from django.db import models

# Create your models here.

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

music/views.py
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from .forms import UserForm
from django.views.generic import View
'''from django.shortcuts import render
from  django.http import  Http404
from  django.template import loader
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from  .models import Album,Song

# Create your views here.

def index(request):
    html = ''
    albums = Album.objects.all();
    #template = loader.get_template('music/index.html')
    context ={
        'all_albums':albums,
    }
    return  render(request,'music/index.html',context);
    #for album in albums:
     #   url = '/music/' + str(album.id) + '/';
      #  html +='<a href="'+ url +'">' + album.album_title + '</a><br>'
   # return HttpResponse(template.render(context,request));

def detail(request,album_id):
    #try:
     #   album = Album.objects.get(pk=album_id)
    #except Album.DoesNotExist:
     #   raise Http404("Album does not exist")
    album = get_object_or_404(Album,pk=album_id)
    return render(request, 'music/detail.html',{'album':album});
    #return HttpResponse("<h1>Album id: " + str(album_id) + "<h1>");



def favorite(request,album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song  = album.song_set.get(pk=request.POST['song'])
    except(KeyError,Song.DoesNotExist):
        return render(request,'music/detail.html',{
            'album': album,
            'error_message':'You did not select valid song'
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {
            'album': album,

        })'''

class IndexView(generic.ListView):
        template_name = 'music/index.html'
        context_object_name = 'all_albums'

        def get_queryset(self):
            return Album.objects.all()

class DetailView(generic.DetailView):
        model = Album
        template_name = 'music/detail.html'

class AlbumCreate(CreateView):
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
        model = Album
        success_url = reverse_lazy('music:index')


class UserFormView(View):
        form_class = UserForm
        template_name  = 'music/registration_form.html'


        def get(self,request):
                form = self.form_class(None)
                return render(request,self.template_name,{'form':form})

        def post(self,request):
                form = self.form_class(request.POST)
                if form.is_valid():
                        user = form.save(commit=False)
                        username = form.cleaned_data['username']
                        password = form.cleaned_data['password']
                        user.set_password(password)
                        user.save()

                        user = authenticate(username=username, password = password)

                        if user is not None:
                                if user.is_active:
                                        login(request,user)
                                        return redirect('music:index')
                return redirect(request, self.template_name, {'form': form})

myapp/views.py
from django.shortcuts import render

# Create your views here.

music/templates/music/album_form.html
    {% extends 'music/base.html' %}

    {% block body %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-7">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% include 'music/form-template.html' %}
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Album
{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}" />
</head>
<body>
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'music:index' %}">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Album<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Show Album</a></li>
          <li><a href="#">Show Song</a></li>

        </ul>
      </li>
      <li><a href="{% url 'music:album-add' %}">Add Album</a></li>
    </ul>

    <form class="navbar-form navbar-left" action="/action_page.php">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>


    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'music:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
 {% extends 'music/base.html' %}

 {% block title %} Album Details
{% endblock %}

 {% block body %}

 <img src="{{ album.album_logo.url }}" class="img-responsive" height="300" width="300">
<h1>Album Title: {{ album.album_title }} </h1>
<h3>Album Artist: {{ album.artist }} </h3>

<!-- <ul>
    {% for song in album.song_set.all %}
    <li> {{song.song_title}} - {{ song.file_type }} </li>
    {% endfor %}
</ul>
-->
{% if error_message %}
    <p>{{error_message}}</p>
{% endif %}

 {% for song in album.song_set.all %}
        {{song.song_title}}
        {% if song.is_favorite %}
                Fav
        {% endif %}
        <br>
 {% endfor %}
  {% endblock %}

music/templates/music/form-template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>

{% endfor %}

music/templates/music/index.html
    {% extends 'music/base.html' %}

    {% block body %}
        <h1>Hello</h1>
        {% if all_albums %}
        <ul>
            {% for album in all_albums %}
            <li>
                <img src="{{ album.album_logo.url }}" class="img-responsive" height="200" width="200">
                <a href="{% url 'music:detail' album.id %}">{{ album.album_title}}</a>
                <form action="{% url 'music:album-delete' album.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{album.id}}">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </li>
            {% endfor %}
        </ul>
        {% else %}
            <h2>There is no album.</h2>
        {% endif %}

    {% endblock %}

music/templates/music/registration_form.html
    {% extends 'music/base.html' %}

    {% block body %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-7">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% include 'music/form-template.html' %}
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endblock %}